### ISSUE TITLE
Cell status wrong

### ISSUE THREAD

**Issue by dakoop** [colinjbrown/dfkernel#110]
1. Create a notebook with four cells `a,b=10,12`, `x=123`, `c=a+x`, `d=a+12`. 
 2. Run all the cells. 
 3. Close the notebook. Re-open it.
 4. Run all the cells in top-down order.
 5. Change the first cell.

Only the first cell will have the changed indicator.

**Comment by colinjbrown** [comment]
This issue was moved to dataflownb/dfkernel#38
