### ISSUE TITLE
Use return syntax for cell output?

### ISSUE THREAD

**Issue by dakoop** [colinjbrown/dfkernel#27]
Instead of using the somewhat opaque last line syntax for deciding what to deem as output for cell, we could also use a return statement and use the ast to unpack this. We would still probably want to limit its use to the last node of the cell, however. Thus, the shorthand
```
u = 3
v = u + 4
u, v
```
could still work, but a user could also write
```
u = 3
v = u + 4
return u, v
```
which might be more intuitive? If we really wanted to be unique, we could add a new keyword (`output`) to make it clear that we are identifying a cell's output:
```
u = 3
v = u + 4
output u, v
```

**Comment by colinjbrown** [comment]
This issue was moved to dataflownb/dfkernel#21
