### ISSUE TITLE
Widgets

### ISSUE THREAD

**Issue by dakoop** [colinjbrown/dfkernel#42]
After playing around with ipywidgets, I have some thoughts on making them work with dfkernel.

1. Widgets should be shown with labels like other outputs (need to redo the widget-specific output area stuff to show the tag), not sure if having them be `execute_result`s or `display_data`s is a big deal
2. A widget's value should be referenced just using the the name of that widget, `x` not `x.value` as is currently done. Any needs for things like links, jslinks, etc. can be done with some type of widget(<name>) call or something.
3. Every widget should have an observer that triggers execution if necessary. Users should also be able to use an `interact_manual` analog so that execution is only triggered when a button is clicked
4. Downstream use of a widget's value is then as simple as `y = x + 4`

**Comment by colinjbrown** [comment]
This issue was moved to dataflownb/dfkernel#26
