### ISSUE TITLE
Configuration/preferences

### ISSUE THREAD

**Issue by dakoop** [colinjbrown/dfkernel#76]
We need to store configuration information for dfkernel that users can update. Flags include:

* force-cached (turn off completely)
* auto-add-libraries
* no-closure (not implemented yet)
* ast-node-interactivity
* show-deleted-cells

We should use BaseJSONConfigManager with jupyter_config_dir stuff to store configuration settings (and mimic how IPython serializes things).

**Comment by colinjbrown** [comment]
This issue was moved to dataflownb/dfkernel#31
