### ISSUE TITLE
Fix formatting for cell inputs/outputs

### ISSUE THREAD

**Issue by dakoop** [colinjbrown/dfkernel#77]
Currently, long names for outputs will exceed the width of the prompt, and the inputs and outputs do not line up with the icons enabled. We need to set widths for these and make sure they line up. Also, we should use `text-overflow: elipsis` for output tags that need elision and put the full name in the title attr.

**Comment by colinjbrown** [comment]
This issue was moved to dataflownb/dfkernel#32
