### ISSUE TITLE
Check if cells exist for updating icons

### ISSUE THREAD

**Issue by HieuNgo** [colinjbrown/dfkernel#79]
When a deleted cell is downstream and you edit the upstream cell, update_icons tries to set an icon for a non-existing cell. We need to check if the downstream cell exists before setting the icon.
![image](https://user-images.githubusercontent.com/24400059/44419577-9bce8a00-a549-11e8-8555-f3bb91be3d9a.png)

**Comment by colinjbrown** [comment]
This issue was moved to dataflownb/dfkernel#33
